///////////////////////////////////////////////////////////
//  AuthenticationSubject.cs
//  Implementation of the Class AuthenticationSubject
//  Generated by Enterprise Architect
//  Created on:      15-Dec-2020 6:44:10 PM
//  Original author: Ahmed
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;

namespace NewsAgencyApp
{
    class AuthenticationSubject : IObservable<AuthenticationState>
    {
        private List<IObserver<AuthenticationState>> observers;

        public AuthenticationSubject()
        {

        }

        public IDisposable Subscribe(IObserver<AuthenticationState> observer)
        {

            return null;
        }

    }
}